---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-codegen-nov524-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-codegen-nov524-1 
  name: test-codegen-nov524-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi